### ISSUE TITLE
License not packaged in pypi release

### ISSUE THREAD

**Issue by cshaley** [joowani/binarytree#12]
The license states that it should be packaged in all distributions of the package, but it is not packaged in the pypi release. I only realized this because I am in the process of [packaging bonarytree for conda forge](https://github.com/conda-forge/staged-recipes/pull/4688).

**Comment by joowani** [comment]
Right... if I remember correctly I was not packaging it correctly for earlier distributions. I will take a look tonight and see if removing the older distributions from pypi fixes the issue. Thanks!

**Comment by joowani** [comment]
@cshaley I've removed all the older distributions from pypi. Let me know if that fixes things. What issue are you having exactly?

**Comment by synapticarbors** [comment]
I believe you need to add a `MANIFEST.in` to the package:

https://docs.python.org/2/distutils/sourcedist.html#specifying-the-files-to-distribute

**Comment by joowani** [comment]
Thanks @synapticarbors. I will take a look and add it.

**Comment by cshaley** [comment]
@joowani FYI, this is not a technical issue so much as a legal one.  Best practice is to always package the license with the software.  Not as big of a deal for something that uses the MIT license as it could be for a package with a custom/pay-for-play license.

**Comment by joowani** [comment]
@cshaley I believe I've corrected the issue. Please let me know if you see any other problems. Thanks!
