### ISSUE TITLE
Build script for archlinux

### ISSUE THREAD

**Issue by joaquingx** [joowani/binarytree#13]
Hey Joowani :),

I just created a build script of this package for archlinux ([PKGBUILD](https://aur.archlinux.org/packages/python-binarytree/)). Maybe you can check if all is ok. If all is good, we can put this build option in README, that would be great for arch users :).

Cheers,
Joaquin

**Comment by joowani** [comment]
Hi @joaquingx! 

Sure I can make a note of it in the README.
I don't have an arch environment set up so it will take a while for me to test it out though.

Thanks for your contribution!

**Comment by joowani** [comment]
Hi @joaquingx,

I've decided not to include any environment specific notes on the README as I don't want to increase my maintenance workload. Feel free to own and maintain the arch build though if you want. Thanks again :)
