### ISSUE TITLE
InvalidNodeValueError: The node value must be an integer

### ISSUE THREAD

**Issue by canturk** [joowani/binarytree#16]
Hi there,
I did not get the reason why the value of  Node class in binarytree must be integer in the new version (3.0.1.), whereas  it worked perfectly for floating point value in the old version (1.1.1).
Can you fix that?
Thanks
MC

**Comment by joowani** [comment]
Hi @canturk,

Sorry for the late response. I can't remember the details on top of my head, but when I allowed arbitrary node values, there were many awkward edge cases that i could not work around (e.g. user-supplied values were complex objects that did not support random generation or comparison). Pretty printing the tree was also an issue when the `__repr__` of values were lengthy (the tree would get really wide). To avoid such future headaches I decided that integer is probably enough for users to practice their algorithms. Floats should be easy to add them back so I will consider it. Just out of curiosity, what is your use case with floats that you can't use ints instead?

Best
Joohwan

**Comment by joowani** [comment]
Hi @canturk,

It's been a while, but I've finally released binarytree 4.0.0 which adds back support for all "number" type node values (e.g. int, float, decimal.Decimal). You can check out the [release notes](https://github.com/joowani/binarytree/releases/tag/4.0.0) for full details. As for accepting other user-defined values, I will have to work out all the kinks before I can allow full customization again (no timeline for this yet). Feel free to re-open this issue or send me a message if you have any other problems!
