### ISSUE TITLE
Feature: Export to graphviz dot format

### ISSUE THREAD

**Issue by villmow** [joowani/binarytree#19]
First of all nice package, thanks for that! I just wanted to visualize a binary tree with Graphviz thats why I adapted [this utility function from the treelib package](https://github.com/caesar0301/treelib/blob/375b9c440972b06198afe4bb8a9deaea04a5163d/treelib/plugins.py#L30), maybe it fits somewhere in your library. As I wanted to have string values for nodes and that doesn't work with your package I supplied an optional `id2name` dictionary, which stores the mapping.

```python
import binarytree as bt

def binarytree_to_dot(root: bt.Node, filename: str, id2name: Optional[Dict[int, str]] = None, 
                      shape: str = 'ellipse', graph: str = 'digraph') -> None:
    """Exports the tree in dot format of the graphviz software. 
    Left childs are denoted by a full stroke arrow, right childs by a dashed arrow."""

    if not isinstance(root, bt.Node):
        raise ValueError("Root must be a binarytree.")
        
    if id2name is None:
        id2name = {node.value: str(node.value) for node in root}
        
    nodes, connections = [], []
    
    for node in root.levelorder:
        nid = node.value
        state = '"' + str(nid) + '"' + ' [label="' + str(id2name[nid]) + '", shape=' + shape + ']'
        nodes.append(state)

        if node.left is not None:
            cid = node.left.value
            connections.append('"' + str(nid) + '":sw' + ' -> ' + '"' + str(cid) + '"')
        if node.right is not None:
            cid = node.right.value
            connections.append('"' + str(nid) + '":se' + ' -> ' + '"' + str(cid) + '"  [style=dashed]')

    # write nodes and connections to dot format
    with open(filename, 'wt') as f:
        f.write(graph + ' tree {\n')
        for n in nodes:
            f.write('\t' + n + '\n')

        f.write('\n')
        for c in connections:
            f.write('\t' + c + '\n')

        f.write('}')
```

## Example Use
Use it like this
```python
root = bt.tree(height=6)
binarytree_to_dot(root, filename="test_tree.dot")
```

After installing graphviz, you can plot the tree with the following command:
```bash
dot -T png -o test_tree.png test_tree.dot
```

which will result in the following image:
![image](https://user-images.githubusercontent.com/2743060/53816571-0d10e000-3f64-11e9-9e3e-5ce4fb286a17.png)

**Comment by joowani** [comment]
Hi @villmow,

Thanks for liking binarytree and this is pretty cool work! 

I have received a few requests for graphviz integration in the past. Right now, however, because of my schedule, I've paused all feature work on my open source projects (PR submissions will also be very slow). If you want to share your work with more people I encourage you to publish your own library built on top of binarytree. I will keep this open for any future updates.

**Comment by joowani** [comment]
Instead of implementing this method from scratch, I've decided to use [python-graphviz](https://pypi.org/project/graphviz) instead (it has many more features) in version 6.0.0. Please see the [documentation](https://binarytree.readthedocs.io/en/main/graphviz.html) for more details!
