### ISSUE TITLE
References for properties

### ISSUE THREAD

**Issue by joaquingx** [joowani/binarytree#2]
Hello, i think that a  short reference for the properties of binary trees will be useful for the purpose of the project.
Something like : 
>>what_is_full()
>> Is a tree in which every node in the tree has either 0 or 2 children.
>> An Example

**Comment by joowani** [comment]
Hi Joaquingx,

I'm not sure if I understand you correctly. Are you talking about adding new functions to the API to separate out what `inspect` already does, or are you talking about adding new parameters to the generate tree functions?

Thanks,
Joohwan

**Comment by joaquingx** [comment]
Hi Joohwan,

I'm talking about to add functions that serves as reference for the user.
For example, if I don't remember what is a _full tree_ , then I can call some function like
`what_is( full )` , and this function returns me the concept of the property(full) and an example(of a full tree).

This with the purpose of a full tool for studying binary trees.

P.s. Newly i figured out that  the word "propertie" doesn't exist :( haha, sorry for my awful english.

**Comment by joowani** [comment]
Hi Joaquingx, 

No problem!
I do like your idea. If I am understanding you correctly, however, the "reference functions" you are talking about would simply print things. It would probably be better to house that kind of information in a wiki or some sort of an external documentation. In the future I plan to add a Github wiki page on documentation on readthedocs.org and add the link to the README!

Thanks,
Joohwan

**Comment by joaquingx** [comment]
Hi Joohwan, I understand. 
I think I cannot help to this.
However, I'll be paying attention to the new issues in this project :).

Thanks,
Joaquin.

**Comment by joowani** [comment]
Awesome! Thanks for your contribution.

Joohwan
