### ISSUE TITLE
Adding a requirements.txt 

### ISSUE THREAD

**Issue by geekypandey** [joowani/binarytree#28]
Hi! Could we add a requirements.txt file for making it easy for new contributors to contribute?

**Comment by joowani** [comment]
Hi @geekypandey,

Sorry for the late reply. I don't think a small library like this one needs a requirements.txt, especially when it has no dependencies at all! Well minus pytest and few others used for testing. I'm hesitant to add more files to maintain without a compelling reason. Thanks.
