### ISSUE TITLE
Tree with strings

### ISSUE THREAD

**Issue by Archerlite** [joowani/binarytree#33]
Hi,

I'm new to github but I just found your project, which really interests me and should make my work easier. 

I've read through the documentation, and I didn't find a way to associate strings to a Node. I actually need it to process the Huffman algorithm, and therefore need to create a tree with each letters of my message and their probability. I've spotted the value of the node could be a float, which fits for the probability, but have you thought about a way to implement strings ? 

I could maybe use ASCII to put integers in place of letters in the tree, but that would require me to attach the weight (probability) to such a node and I did not find out if that was possible either. 

Could you help me better understanding your library ?
Thank you very much !

**Comment by yuanchaomin** [comment]
> Hi,
> 
> I'm new to github but I just found your project, which really interests me and should make my work easier.
> 
> I've read through the documentation, and I didn't find a way to associate strings to a Node. I actually need it to process the Huffman algorithm, and therefore need to create a tree with each letters of my message and their probability. I've spotted the value of the node could be a float, which fits for the probability, but have you thought about a way to implement strings ?
> 
> I could maybe use ASCII to put integers in place of letters in the tree, but that would require me to attach the weight (probability) to such a node and I did not find out if that was possible either.
> 
> Could you help me better understanding your library ?
> Thank you very much !

Hi  Archerlite,  I am also interesting for this project. Facing the same problem like you, I would like to associate strings to a Node, thus I make a little bit change of the original code and make it support representing letters.  Here is the link https://github.com/yuanchaomin/binarytree,  However, it is just a workaround and  may contain lots of bugs,  hope it helps.

**Comment by joowani** [comment]
Hi @Archerlite and @yuanchaomin,

Sorry for the delay. I have considered strings in the past but ran into multiple issues I didn't have the time to resolve (e.g. the tree becomes too wide with multi-character strings, randomly generating unique strings, node comparisons). I will make this as a feature.

**Comment by joowani** [comment]
Hi @Archerlite and @yuanchaomin,

String support has been added in the latest release of binarytree [6.5.0](https://github.com/joowani/binarytree/releases/tag/6.5.0)!
