### ISSUE TITLE
Docs request: link readthedocs page at the top of README

### ISSUE THREAD

**Issue by jamesbraza** [joowani/binarytree#36]
I am a new user of `binarytree` and it's saving me some time in an algorithms class, so thank you!

Originally, I was scrolling up and down in the `README.md` a bunch, before I noticed the [binarytree.readthedocs.io](http://binarytree.readthedocs.io/) link on the right.  The API Specification page was exactly what I was looking for.

Take a look at `README` of popular repos:
- https://github.com/PyCQA/isort
- https://github.com/python/mypy
- https://github.com/PyCQA/flake8

They all clearly have the docs hosting linked at the top of the `README`, which makes it very easy to discover the docs.  I think `isort` does the best job of this.

I think it would be helpful for `binarytree` to do the same.  Thank you for your consideration!

**Comment by joowani** [comment]
Done!
