### ISSUE TITLE
Documentation is missing explanation if this data structure keeps the data balanced (red-black, AVL) or not.

### ISSUE THREAD

**Issue by ndvbd** [joowani/binarytree#37]
Documentation is missing explanation if this data structure keeps the data balanced (red-black, AVL) or not.

If it's NOT, better to explicitly say in the very first few lines of the readme.

**Comment by joowani** [comment]
Hi @ndvbd,

Do you mean if the generation of random trees can guarantee balanced-ness?

**Comment by ndvbd** [comment]
Exactly

**Comment by joowani** [comment]
Done!
