### ISSUE TITLE
is_bst returns incorrect result

### ISSUE THREAD

**Issue by hmuar** [joowani/binarytree#8]
I'm not sure if the current way of calculating the `is_bst` property is correct. I thought for a bst, ALL nodes in left subtree should be less than parent, and ALL nodes in right subtree should be greater than (and possibly equal to if you want to allow duplicate keys) parent.

Seems like the current method only compares immediate left and right nodes to parent, so an example like this tree fails with current method:

```
    __ 2
 /       \
1         4
 \
  3
```

```python
from binarytree import tree, convert, inspect
nodeList = [2, 1, 4, None, 3]
tree = convert(nodeList)
tree_props = inspect(tree)
assert(tree_props['is_bst'] == False)
```

**Comment by joowani** [comment]
Hi @hmuar,

Yes good catch! It was indeed calculating incorrectly. I've fixed the issue in the latest release [2.0.1](https://github.com/joowani/binarytree/releases/tag/2.0.1).
Please try running `pip upgrade binarytree` and let me know if there is anything else wrong.

Thanks!
Joohwan
