### ISSUE TITLE
Additional functionality

### ISSUE THREAD

**Issue by cshaley** [joowani/binarytree#9]
Here's a brief list of functionality that I think would be really awesome to include in this library.  Any feedback would be greatly appreciated.  I'll get to these eventually if @joowani likes them and if no one gets to them first!

1. Parent node attribute functionality for each node. e.g. tree.right.right.left.parent
2. Level attribute functionality for each node.  e.g. tree.right.right.level
3. A function for returning all nodes at each level.  e.g. bt.get_level(tree, 6)
4. Index nodes by value or ID.  e.g. tree["my node value"] or tree[6].  I'm thinking the second one makes more sense as a tree could potentially have the same value at different nodes.

**Comment by joowani** [comment]
Hi @cshaley,

Thanks for your suggestions. They sound great. Feel free to send me pull requests and I'll be happy to take a look!

Best,
Joohwan

**Comment by cshaley** [comment]
@joowani Currently, the id is not a stored attribute of each node.  In order to index nodes by ID, with something like `tree[6]`, I think I'll need to have one of the below two designs:

1. A defined structure for node IDs, such as 0 for the root, 1 for the left, 2 for the right, then 3, 4, 5, 6 for the next level, etc. where nodes get assigned IDs based on their locations.  e.g. Not having a node at location 5 doesn't mean that the node ID for location 6 will change.
2. A unique ID attribute assigned to each node upon its creation.

I tend to favor the first approach, though I certainly see benefits of the second.  What are your thoughts?

**Comment by joowani** [comment]
Hi @cshaley 

Binarytree uses [level order traversal](http://www.geeksforgeeks.org/level-order-tree-traversal/) to determine or assign the node IDs. I believe this is equivalent to what you are suggesting in your bullet point 1. You can check out how I dynamically assign the IDs in `show_ids` method, and use that as a basis to override the `__getitem__` method.

Best,
Joohwan

**Comment by cshaley** [comment]
So assign IDs based on level order traversal at time of function call? That's how ID assignment works now.  This could be unintuitive.  e.g. if I have a root node, and a node to its right, then those are IDs 0 and 1.  If I then insert a node to the root's left, they have respective IDs 0, 1, and 2.  So the ID of the node to the right of the root has changed, and ID 1 now refers to a different node from before.  I would consider that to be unexpected behavior because object IDs are typically thought of as immutable.

If you originally assign the root 0 and the right 2 (based on location), then you avoid this issue.  Node IDs would then only change when moving nodes around.

**Comment by joowani** [comment]
Ah I see what you mean. I really like that idea (referring to the location based, fixed IDs). It would be a nice upgrade from the naive level order ID assignment I have going right now. 👍

**Comment by cshaley** [comment]
I want to outline expected behavior and make sure you're on the same page before I code it up fully.

In:
't = convert(list(range(10)))
bt.show_ids(t)
'
Out:
'
        ____0__    
       /       \   
    __1__       2  
   /     \     / \ 
  3       4   5   6
 / \     /         
7   8   9          '

In: `t[5]`
Out: `Node(5)`

In: `t[10]`
Out: `IndexError: No node at specified location.`
Should this just return None instead? Then you could say `if t[10] is None: t[10] = Node(10)`.  It'd be pretty clunky to have to use a try except clause to find blank spaces in a tree.  But what if someone puts blank Nodes into a tree? i.e. Node(None).  Not throwing an error here would cause issues.

In: `t[10] = 10`
This sets the value of the node in location 10 to 10.  This does not replace the node, but rather replaces its value.  That way you don't lose its descendants.  If you want to prune descendants, you can do so with an explicit prune or by setting right and left to None.

In: `t[10] = Node(10)`
This sets the value of the node in location 10 to Node(10).  This does not replace the node, but rather replaces its value.

Building a tree with the build list with IDs method should follow the same fixed-location ID protocol as outlined in previous comments.  Anything else that references IDs should follow suit.

**Comment by joowani** [comment]
In: `t[5]`
Out: `Node(5)`
**Yup this is fine**

In: `t[10]`
Out: `IndexError: No node at specified location.`
**Hmm I prefer raising an exception. It stays true to the expected behavior of the builtin index method.**

In: `t[10] = 10`
**I actually think this should raise an exception saying only instances of Node (or the user's custom node class if set) are accepted. As for changing the value, you can always just do t[10].value = 10.**

In: `t[10] = Node(10)`
**Changing only the value here will go against the expected assignment behavior. This should replace the entire subtree. As mentioned above you can always just do t[10].value = 10 if you want to update the value quickly.**

**Comment by cshaley** [comment]
Okay, agreed on all points.  Well-thought out.
